### ISSUE TITLE
Secure gRPC channel

### ISSUE THREAD

**Issue by MuhammadMoustafa** [socotecio/django-socio-grpc#121]
Hello, 

I hope you are doing well.
First of all, thanks for your efforts.

I noticed that you are using add_insecure_port in the server initialization found in _server function in grpcrunaioserver.py
What should be done if I want to override these settings and use a secure port?
I want to use SSL/TLS encryption mechanism mentioned In this [link](https://grpc.io/docs/guides/auth/)

I also notice that the authentication page in the documentation is still empty. Are there any plans to fill it soon?

Thanks,

**Comment by AMontagu** [comment]
Hello @MuhammadMoustafa 

I think there is two ways of doing it. Adding it to the commend arguments directly or in the grpc_settings.
The best would have to have both. Taking the argument first, if not existing using the grpc_settings and if not set open an insecure_port.

Be aware that this encryption is used for end to end encryption. If your grpc server is behind a proxy that use a SSL certificate you don't need it to protect the data send by client from external source.

In the other side we support django authentication mechanisme using the `Authentication` header key but I didn't had the time to write the documentation about it.
You have an example here: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/tests/test_authentication.py#L98

You also, as DRF, need to set you rauthentication and permissions classes. We have global settings like `DEFAULT_AUTHENTICATION_CLASSES` and `DEFAULT_PERMISSION_CLASSES` or service attribute like `authentication_classes` and `permission_classes` to deal with auth. To learn more about that please read DRF documentation:
https://www.django-rest-framework.org/api-guide/authentication/

We are compatible with already existing DRF classes using the Authentication like https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication for exemple.
We basically just get the metadata `HEADERS` key and put it in the django request that is then used by the differents authentication classes.

Pagination and filterings use the same mechanismes to be compatible with librairy as django-filters.

If you need help on the authentication part do not hesitate to publish code with what you are trying to do and will try to have a look.

Be aware that sessionauthentication may not work as we never used it and it may some work to simulate an HTTP session in the gRPC server. And we may not want to do that as gRPC has been designed to be stateless.
