### ISSUE TITLE
Traceback issues

### ISSUE THREAD

**Issue by nguthiru** [socotecio/django-socio-grpc#149]
Hello, I am using python 3.10 and I am ending up with the error, "<class 'TypeError'>: print_exception() got an unexpected keyword argument 'etype'"". To fix this I have removed the keyword parameter etype in the log_unhandled_exception function.

Sorry if its unreadable its my first time doing this.

**Comment by AMontagu** [comment]
Hello @nguthiru 

Indeed, Look like python change the traceback.print_exception interfcae in python 3.10. Will check how to make it work properly.

**Comment by AMontagu** [comment]
Hello @nguthiru the fix is available in the 0.18.0rc5 version. Please note that it's a release candidate version so to install it you will need to specify to your packet manager (pip, poetry, pipfile, ...) that this is a pre release version.
