### ISSUE TITLE
Exception when use generics.AsyncRetrieveService

### ISSUE THREAD

**Issue by adomigold** [socotecio/django-socio-grpc#153]
Hello again,
i got this exception when i use AsyncRetrieveService on services ```django_socio_grpc.protobuf.exceptions.ProtoRegistrationError: [SignIn.Retrieve]'id'``` What im i doing wrong

```
class SignInService(generics.AsyncRetrieveService):
    """
    gRPC service that allows users to be retrieved or updated.
    """
    serializer_class = SigInSerializer
    queryset = UserProfile.objects.filter(is_active=True)
```

**Comment by adomigold** [comment]
Hey my mistake again i just saw i exclude id on my serializer

**Comment by adomigold** [comment]
Hello,
I solved the above issue but now i got ```AttributeError: 'SigInSerializer' object has no attribute 'amessage'```

**Comment by AMontagu** [comment]
You are not inheriting SigInSerializer from ModelProtoSerializer or from ProtoSerializer

See https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/proto_serializers.py

**Comment by adomigold** [comment]
Hello, I figure it out how to do it
