### ISSUE TITLE
How to perform custom validation on ModelProtoSerializer

### ISSUE THREAD

**Issue by adomigold** [socotecio/django-socio-grpc#154]
Hi, in my serializer class i want to perform a custom validation. In django rest_framework we can do that by using method validate(),
but i could not figure out to do it with django-scoio. Here are my files
```python
# services.py
class SignInService(generics.AsyncRetrieveService):
    """
    gRPC service that allows users to be retrieved or updated.
    """
    serializer_class = SignInSerializer
    queryset = UserProfile.objects.all()
    lookup_field = 'email'
```
```python
# serializers.py
class SignInSerializer(proto_serializers.ModelProtoSerializer):
    class Meta:
        model = UserProfile
        exclude = ['password', 'is_staff', 'verified', 'is_active']
        proto_class = account_pb2.SignInResponse

    def validate(self, attrs):
        if not self.instance.check_password(attrs['password']):
            raise proto_serializers.ValidationError('Incorrect password')
        return attrs
```

On lookup_field, if use lookup_fields and pass email and password it generates only id but if i pass only email it generate email

**Comment by AMontagu** [comment]
Hello @adomigold 

Not sure to understand your issue here. Validate should work as expected. Did you try checking if the method validate was called by using a print or a debugguer ?

Can you describe exactly what are the data that you are sending in the grpc message and what answer you are expected ?

**Comment by adomigold** [comment]
First i was trying to generate proto file with custom lookup_fields. But if i use ```lookup_field = 'email'``` it work as expected it generate email field at SignInRequest method in proto file but when i use ```lookup_fields = ('email', 'password')``` it does not generate those fields instead it generate id field in proto file

**Comment by AMontagu** [comment]
Please be aware that the Viewset (or service in DSG) inherit from MultipleFieldLookupMixin that you need to implement manually. It's not supported out of the box. 
And that so indeed we do not support this for the retrieve. 

You can use grpc_action decorator to customize our behavior as wanted:
https://socotecio.github.io/django-socio-grpc/generate_proto/#adding-custom-method-decorator

example: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/tests/fakeapp/services/basic_service.py

**Comment by adomigold** [comment]
Hello thank again for the reference i follow the instruction and it works but i got issue here on my service
```python
# services.py
class SignInService(generics.GenericService):
    """
    gRPC service that allows users to be retrieved or updated.
    """
    @grpc_action(request=[{"name": "email", "type": "string"}, {"name": "password", "type": "string"}], response=SignInSerializer,)
    async def SignIn(self, request, context):
        user = await sync_to_async(UserProfile.objects.filter(email=request.email).first)()
        serializer = SignInSerializer(user)
        data = await sync_to_async(serializer.data)()
        return data
```
on the line ```data = await sync_to_async(serializer.data)()``` i got this error ```TypeError: sync_to_async can only be applied to sync functions.```  which i don't understand why, can you help me on what i did wrong?

**Comment by AMontagu** [comment]
serializer.data is not an async function.

Please considering testing the following:

```
# services.py
class SignInService(generics.GenericService):
    """
    gRPC service that allows users to be retrieved or updated.
    """
    @grpc_action(request=[{"name": "email", "type": "string"}, {"name": "password", "type": "string"}], response=SignInSerializer,)
    async def SignIn(self, request, context):
        user = await UserProfile.objects.filter(email=request.email).afirst()
        serializer = SignInSerializer(user)
        return await serializer.amessage
```

**Comment by adomigold** [comment]
Thank you man i think that is really helpful :)
