### ISSUE TITLE
Frontend for grpc application

### ISSUE THREAD

**Issue by scout-d** [socotecio/django-socio-grpc#159]
Hello! I was wondering if there was a way to run a frontend for an application without running both `python manage.py runserver` and `python manage.py grpcrunaioserver`. Is that possible? Or is the grpc server strictly for handling rpcs?

**Comment by AMontagu** [comment]
If you don't need any REST call you can just launch `python manage.py grpcrunaioserver` without the runserver.

If you want to launch both with only one command there is some projects around that but not very maintain. It's better to use envoy proxy. See: https://github.com/socotecio/django-socio-grpc/issues/120#issuecomment-1364717458

**Comment by AMontagu** [comment]
close due to inactivity
