### ISSUE TITLE
How to handle validation errors on my project

### ISSUE THREAD

**Issue by adomigold** [socotecio/django-socio-grpc#161]
Hello,
I hope you doing great. I have a sigin function and i want to return a json to tell user that the the password entered is wrong but i cant figure. For now i raise ValueError but that is not i want to do.
Here is my service
```
class SignInService(generics.GenericService):
    """
    gRPC service that allows users to be retrieved or updated.
    """
    @grpc_action(
        request=[
            {"name": "email", "type": "string"},
            {"name": "password", "type": "string"},
            {"name": "passcode", "type": "int32"},
        ],
        response=SignInSerializer
    )
    async def SignIn(self, request, context):
        user = await UserProfile.objects.filter(email=request.email).afirst()

        if user and user.check_password(request.password):
            serializer = SignInSerializer(user)
            return await serializer.amessage
        raise ValueError('Invalid credentials')
```

**Comment by AMontagu** [comment]
Hello @adomigold 

Not sure about this. gRPC is a strict request/answer protocol so you can send json if not defined in your proto and grpc abort method (called when exception) only take a string.

Two options to you: stringify you json and send it has the details the error. Or add an extra field in your SignInSerializer that is a jsonField in read_only and do not raise an error but return the serializer empty with only this json field filled.

**Comment by adomigold** [comment]
Is it possible to do that?? because my SignInSerializer is model-based serializer

**Comment by AMontagu** [comment]
You can inherit from it and add your own fields yes. 
Maybe try the first solution by stringify your return message. It will be more pythonic to raise an exception than to fail silently but both can be done.

**Comment by adomigold** [comment]
Thanks, man for the support it worked.
