### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by ghazalmohseni7** [socotecio/django-socio-grpc#164]
my database is mongodb and i  connect project with mongoengine . i want to use this library and mongoengine together . my model is : 
from mongoengine import DynamicDocument
class Setting(DynamicDocument):
    sms = BooleanField(default=True)
    active = BooleanField(default=True)

and when i run python manage.py generateproto i received : 
raise ProtoRegistrationError(
django_socio_grpc.protobuf.exceptions.ProtoRegistrationError: [Setting.PartialUpdate]'MetaDict' object has no attribute 'concrete_model'

is this library compatible with nosql databases ?

**Comment by AMontagu** [comment]
Hello @ghazalmohseni7 

We never tried with other classe than django.db.models. We use some of this functionnality to make the magic work. 
In your example we try to retrieve the pk of the model that is not required in nosql I suppose. 

If you can provide a minimal repo with a docker-compose than launch everything I think I can try to adapt the code to make it work with mongoengine and defaulting some behavior.

Be aware than by it's structure some auto fonctionnality like finding the pk of the models will not be working.

**Comment by AMontagu** [comment]
close due to inactivity
