### ISSUE TITLE
Model fields' default values not being used for optional fields in version 0.19.0 

### ISSUE THREAD

**Issue by naveenmraja** [socotecio/django-socio-grpc#171]
How to handle non-null model fields that are not set in the request to use the model field's default value? It is working fine in version 0.17.3 but in 0.19.0, it's throwing ValidationError saying `'This field may not be null.'` eventhough there's a default value defined in model definition. Sample code : 

```python
class Merchant(models.Model):
    id = ShortUUIDField(length=16, max_length=25, prefix="merchant_", primary_key=True, editable=False)
    merchant_id = models.CharField(max_length=36, unique=True)
    merchant_name = models.CharField(max_length=256)
    is_verified = models.BooleanField(default=False)
    email = models.EmailField()
    authorized_amount = MoneyField(max_digits=14, decimal_places=3, default=0, default_currency="USD")
```
```python
class MerchantProtoSerializer(proto_serializers.ModelProtoSerializer):
    class Meta:
        model = Merchant
        proto_class = pb2.Merchant
        proto_class_list = pb2.MerchantListResponse
        fields = "__all__"
```
In this case if optional fields is_verified and authorized_amount are not sent in the request, validation error is thrown even with the presence of default values(False and 0 USD). How is this supposed to be handled?

**Comment by legau** [comment]
For now the `ProtoSerializer` always converts unset optional values to `None`, there should be a check on its fields if `allow_null=True`.


As a workaround add

**Comment by naveenmraja** [comment]
> In 0.17.3 it worked because your default values (False and 0) are also the default grpc values for those types.

Nope, currently we have fields with default values other than grpc defaults. We use True, 500 as default values in some model fields and it's working fine in 0.17.3

**Comment by legau** [comment]
As a temporary workaround in your serializer test this code : 
```python
class MerchantProtoSerializer(proto_serializers.ModelProtoSerializer):

    def message_to_data(self, message):
        data = super().message_to_data(message)
        for field_name, field in self.fields:
            if not message.HasField(field_name) and not field.allow_null:
                del data[field_name]

        return data

    class Meta:
        model = Merchant
        proto_class = pb2.Merchant
        proto_class_list = pb2.MerchantListResponse
        fields = "__all__"
```

**Comment by legau** [comment]
Are you sure your 500 is not converted to 0 when you don't send a value in the request ? Looking at the code it would seem to behave this way

**Comment by naveenmraja** [comment]
> Are you sure your 500 is not converted to 0 when you don't send a value in the request ? Looking at the code it would seem to behave this way

Nope, I just checked. It's giving out 500 in both response and the db has 500 too

**Comment by naveenmraja** [comment]
> As a temporary workaround in your serializer test this code :
> 
> ```python
> class MerchantProtoSerializer(proto_serializers.ModelProtoSerializer):
> 
>     def message_to_data(self, message):
>         data = super().message_to_data(message)
>         for field_name, field in self.fields:
>             if not message.HasField(field_name) and not field.allow_null:
>                 del data[field_name]
> 
>         return data
> 
> ```

Had to make a small change but this seems to pass all my test cases :

```python
def message_to_data(self, message):
    data = super().message_to_data(message)
    optional_fields = filter(lambda field: field.has_presence, message.DESCRIPTOR.fields)
    optional_field_names = [field.name for field in optional_fields]
    for field_name, field in self.fields.items():
        if field_name in data and field_name in optional_field_names and not message.HasField(
                field_name) and not field.allow_null:
            del data[field_name]
    return data
```
