### ISSUE TITLE
Please update documentation(Quickstart Guide): AppHandlerRegistry

### ISSUE THREAD

**Issue by markdoerr** [socotecio/django-socio-grpc#176]
Dear Developers, 
I followed the Quickstart Guide and used the "django_socio_grpc.utils.servicer_register " as described in:

`# quickstart/handlers.py
from django_socio_grpc.utils.servicer_register import AppHandlerRegistry
from quickstart.services import QuestionService`

But received a "deprecation" message because "AppHandlerRegistry" moved to a new module.

Please update the examples. Thanks !

**Comment by AMontagu** [comment]
Fixed in last doc release. Thank for your issue.

**Comment by markdoerr** [comment]
Thanks @AMontagu :)
