### ISSUE TITLE
docs: Proto serializer - tips: UUID field - please improve explaination

### ISSUE THREAD

**Issue by markdoerr** [socotecio/django-socio-grpc#182]
Hi developers,
testing the **django-socio-grpc** framework I realised an issue with sending primary keys (in my case they are UUIDs) as foreign keys.

I found this remark in the proto serializer documentation:

`related_object = serializers.PrimaryKeyRelatedField(
    queryset=Something.objects.all(),
    pk_field=UUIDField(format="hex_verbose"),
)
`
Could you please explain, where this code should go  (which module) ?
Could you maybe make an example (like a very simple step-by-step explaination) ?

That would be very helpful. 

Thanks a lot !

**Comment by AMontagu** [comment]
Hi @markdoerr 

Yes of course. We personnaly use UUID so we face this issue a lot. UUID are not a proto class that is serializable as it by protobuf so we have to format it. Fortunatly DRF provide support for it. If you go to: https://www.django-rest-framework.org/api-guide/relations/#primarykeyrelatedfield and read the arguments section you will see the pk_field argument explanation.

It simply allow to serialize type within the serializer before exporting it to protobuf.

@legau can you add this in your documentation plan that you present next week if not already done ?

**Comment by markdoerr** [comment]
Merci beaucoup, @AMontagu,
for the explanation. I will have a look there. 
Nonetheless it is a good idea an example to the documentation - @legau thanks for that in adance :)

**Comment by AMontagu** [comment]
@markdoerr if it's okay for you I close this issue. When doc are finish and this is still missing you will be able to reopen :)
