### ISSUE TITLE
How can this be used in conjunction with django-filter?

### ISSUE THREAD

**Issue by lzy350593418** [socotecio/django-socio-grpc#199]
import django_filters

class ProductFilter(django_filters.FilterSet):
    class Meta:
        model = Product
        fields = ['name', 'price', 'manufacturer']

def product_list(request):
    filter = ProductFilter(request.GET, queryset=Product.objects.all())
    return render(request, 'my_app/template.html', {'filter': filter})

**Comment by legau** [comment]
Hi, 
you can declare your filters the same way as in DRF https://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend

Like so 
```python
class ProductService(generics.GenericService):
    filter_backends = [DjangoFilterBackend]
    filterset_class = ProductFilter
```

**Comment by lzy350593418** [comment]
> Hi, you can declare your filters the same way as in DRF https://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend
> 
> Like so
> 
> ```python
> class ProductService(generics.GenericService):
>     filter_backends = [DjangoFilterBackend]
>     filterset_class = ProductFilter
> ```

I saw that the source code does not handle the filterset_class logic. Do I need to add this logic 
`filter_queryset = BookFilter({'min_price': 100}, queryset=querysrt)`?


```
from django_filters import rest_framework as filters
from book.models import Book


class BookFilter(filters.FilterSet):
    min_num = filters.NumberFilter(field_name="num", lookup_expr='gte')
    max_num = filters.NumberFilter(field_name="num", lookup_expr='lte')

    class Meta:
        model = Book
        fields = ['name', 'pub_date']





    async def List(self, request, context):
        """
        List a queryset.  This sends a message array of
        ``serializer.Meta.proto_class`` to the client.

        .. note::

            This is a server streaming RPC.
        """
        queryset = await sync_to_async(self.get_queryset)()
        queryset = await self.afilter_queryset(queryset)
        queryset = await self.filterset_class({'min_num': 100}, queryset=queryset)
        page = await sync_to_async(self.paginate_queryset)(queryset)
        if page is not None:
            serializer = await self.aget_serializer(page, many=True)
            message = await serializer.amessage
            if hasattr(message, "count"):
                message.count = self.paginator.page.paginator.count
            return message
        else:
            serializer = await self.aget_serializer(queryset, many=True)
            return await serializer.amessage
```

**Comment by AMontagu** [comment]
@lzy350593418 Not sur about what is your issue here.

the filter is done by `queryset = await self.afilter_queryset(queryset)` you should not call an other `queryset = await self.filterset_class({'min_num': 100}, queryset=queryset)`

But you indeed need to set you filters into a metadata filter key name FILTERS. 
See here for a  python example: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/tests/test_filtering.py

**Comment by markdoerr** [comment]
This might also answer my question, @AMontagu (in the examples repo) :) - I will test it.
