### ISSUE TITLE
custom methods

### ISSUE THREAD

**Issue by lzy350593418** [socotecio/django-socio-grpc#200]
If custom methods are needed and the CRUD methods are not required, how can they be set up and how can custom methods be generated when executing python manage.py generateproto?

**Comment by AMontagu** [comment]
Hello,

You have to inherit from django_socio_grpc.generics.GenericService and use grpc_action decorator to declare new service.

Example here: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/tests/fakeapp/services/basic_service.py even if it inherit from mixin just chang to inherit from GenericService

**Comment by lzy350593418** [comment]
> Hello,
> 
> You have to inherit from django_socio_grpc.generics.GenericService and use grpc_action decorator to declare new service.
> 
> Example here: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/tests/fakeapp/services/basic_service.py even if it inherit from mixin just chang to inherit from GenericService

Thanks
