### ISSUE TITLE
Incomplete generation for Request and Response

### ISSUE THREAD

**Issue by rangzen** [socotecio/django-socio-grpc#207]
Hello, is the generate complete?

I have a partial generation, the ObjectRequest and ObjectResponse are not generated.
In the `object_pb2_grpc.py`, calls to ObjectRequest.SerializeToString and ObjectResponse.FromString are wrong.
I cannot either use proto_class and proto_class_list like the tutorial.

Thank you!

Configuration with venv is:
Python 3.11.5
asgiref             3.7.2
Django              4.2.5
django-socio-grpc   0.19.6
djangorestframework 3.14.0
grpcio              1.58.0
grpcio-tools        1.58.0
lark-parser         0.12.0
pip                 23.2.1
protobuf            4.24.3
pytz                2023.3.post1
setuptools          65.5.0
sqlparse            0.4.4

**Comment by AMontagu** [comment]
Hello @rangzen 

The generation process is full. Maybe you run into an exception while generating.
Can you provide a minimal reproduction repo ? Or at least the code you use and the output of the generateproto command ?

**Comment by AMontagu** [comment]
Did you register you new service correctly ? It need to be registered in the grpc_handler method as described here:  https://socotecio.github.io/django-socio-grpc/#quickstart in the Register Service subpart

**Comment by rangzen** [comment]
Hello @AMontagu, sorry for the delay. We tried another way of doing it so I don't thing we have this code anymore. The service was registered. I close this issue. Sorry for the "noise".
