### ISSUE TITLE
bug: fix uppercase of 'FILTER' keyword in tests

### ISSUE THREAD

**Issue by markdoerr** [socotecio/django-socio-grpc#209]
'FILTER' keyword should be lower case in filter definitions.

**Comment by legau** [comment]
The expected behavior is that metadata keys should work both as uppercase or lowercase

**Comment by AMontagu** [comment]
@legau this issue is meant in the clients. And grpc is only working with lower case metadata. If it's working in our env it's because in your api client we make sure it's lower string before sending them. We need to update doc/exemple to be sure everything is in lower case

**Comment by AMontagu** [comment]
https://github.com/socotecio/django-socio-grpc/commit/14b48c9ab753971503883527677c514a55edb4df

Should be enough to fix this issue

**Comment by legau** [comment]
Seems to be HTTP/2 https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2
