### ISSUE TITLE
Finish new RTD doc

### ISSUE THREAD

**Issue by AMontagu** [socotecio/django-socio-grpc#220]
Missing steps:

- [x] Merging all remaining doc page
- [x] Merging RTD branch
- [x] Deleting old doc conf file like mkdocs.yml
- [x] Improving CI or readme to check if RTD build failed
- [x] Global review from @legau and @AMontagu

**Comment by markdoerr** [comment]
@AMontagu  and @legau,
please consider my suggestions (#206) for the next documentation release , merci. :)

**Comment by AMontagu** [comment]
@markdoerr your suggestions are merged/reviewed. Thank you !

**Comment by markdoerr** [comment]
Merci, @AMontagu,
yes, let's refine from the merged version....

**Comment by AMontagu** [comment]
No easy way to check in CI if doc passed.
Added email notification if fail + readme badge. Should be enough
