### ISSUE TITLE
model fields with default values -> shoud be generated as "optional" in the proto file

### ISSUE THREAD

**Issue by markdoerr** [socotecio/django-socio-grpc#227]
Hi,
in the current implementation, model fields with a _default value_ will be generated as "mandatory" in the proto file (see, e.g. 
[model.py](https://github.com/socotecio/django-socio-grpc-example/blob/feature/async_example_bibliography/backend/example_bib_app/models.py)
and the
[generated proto file](https://github.com/socotecio/django-socio-grpc-example/blob/feature/async_example_bibliography/backend/example_bib_app/grpc/example_bib_app.proto)

Expected behavior:
Since there is default value provided for this field, it should be **optional** to provide a different value.

**Comment by legau** [comment]
Same as #171
