### ISSUE TITLE
improve object creation speed

### ISSUE THREAD

**Issue by markdoerr** [socotecio/django-socio-grpc#260]
Hi @AMontagu  and @legau,

in the examples repo, I added an example notebook, where 1000 book entries are created:

https://github.com/socotecio/django-socio-grpc-example/pull/16/commits/9b66bf5ab90b3d12d69bcff0c20ca437aa31568e

The 1000 entries took 40 seconds on my computer without gathering and with gathering approx. 34 seconds.
It feels rather slow (django / postgres should manage much higher throughput).

How can the creation speed be improved ? 
Where are the bottlenecks ?

(shouldn't we reach 10.000 entries per second at least ?)

**Comment by legau** [comment]
Hi @markdoerr ,
I looked into it and the project is not using postgres but sqlite so the performance is subpar.
I made this branch https://github.com/socotecio/django-socio-grpc-example/tree/use-postgres with postgres and a new BookViewSet from base DRF to do a bit of benchmark.
You can see it being about 4 times faster. However as demonstrated by this test and the REST route I added in DRF, Django and DRF are slow web frameworks by essence. The usual way of speeding things up is by horizontally scaling these apps so they can handle much more rps.

**Comment by markdoerr** [comment]
Thanks for the fast reply, @legau ,
I will try it as soon as I mange.
So you believe, the bottleneck is the underlying DjangoRestFramework ?
Do you already have a suspicion, which parts of the DRF slows everything down so dramatically ?
Are these the Serializers / Deserializers ?
If yes, we have a new topic for a master thesis ;)

**Comment by markdoerr** [comment]
Hi @legau,
I think, you forgot to add the "rest_framework/api.html" template.
This is at least the error, you see in the browser, when you run your example.
If yes, could you quickly add it ? Thanks :)

**Comment by markdoerr** [comment]
Hi @legau, 
I tested your example on my machine and compared 
DSG vs native django API (no networking, just to see, what to expect) with postgres vs sqlite for 1000 Authors 

native django / postgres  (sync mode) : ca. 3 s
native django / SQLite (sync mode) : ca. 15 s

DSG: postgres & async - gather : ca. 15 s
DSG: SQLite &  async - gather : ca. 40 s

DRF I have not yet tested.

=> postgres is definitely faster, there are bottlenecks in the DSG / DRF creation pipeline that could be improved.

The next steps would be to detect these bottlenecks.

**Comment by AMontagu** [comment]
Hello @markdoerr 

Yes DSG is know to be slow. Mostly on the serialization/deserialization process on the ModelSerializer because it automatically add lot of constraints check. 
There is a lot of performance gain possible and a lot of article on this subject: https://hakibenita.com/django-rest-framework-slow. As we rely on DRF serializer almost all advices are good to use with DSG.

 The longer plane (mostly in 2.0.0) is to rewrite the serializer class from DRF to directly use grpc object instead of transforming it to python dictionnary. But this is a big task.

**Comment by AMontagu** [comment]
@markdoerr do you think we can close this issue or do you want to add more context or require action ?

**Comment by markdoerr** [comment]
Salut @AMontagu,
thanks for the link above ! I will have a look into the recommendations there.
I am glad, that you are planning a re-write.
So for now, you can close the issue.
If I figure out important details, I will let you know :)
