### ISSUE TITLE
FakeRpcError missing from new version

### ISSUE THREAD

**Issue by lidiador** [socotecio/django-socio-grpc#268]
Our project used FakeRpcError from django_socio_grpc.tests.grpc_test_utils.fake_grpc in some unit tests, but it appears to be missing from the current version, so we can't bump the djang-socio-grpc version used in the project, Is it deprecated and do you recommend using something else instead?
![image](https://github.com/socotecio/django-socio-grpc/assets/4425347/4c49f4bb-afbe-42fe-9816-b6904d8f05e6)

**Comment by AMontagu** [comment]
Hello @lidiador 

We improved our test system to directly use `grpc.RpcError` (import grpc).
It will be closer to reality.
Can you test it and validate it is good for you ?

**Comment by lidiador** [comment]
Hello, @AMontagu ,

Inital tests indicate that it looks good, the error is imported and the tests work as they did before.
Thank you very much!

Mateusz
