### ISSUE TITLE
Deprecated including_default_value_without_presence_fields in with Protobuf 5.26.1.

### ISSUE THREAD

**Issue by xaviave** [socotecio/django-socio-grpc#291]
This flag has been deprecacted in the last protobuf version v27.0 and throw an exception if BaseProtoSerializer is used.

`TypeError: MessageToDict() got an unexpected keyword argument 'including_default_value_fields'`

Can be resolved with removing this line in [json_format.py:message_to_dict](https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/protobuf/json_format.py):
`kwargs.setdefault("including_default_value_fields", True)`
And updating protobuf >= 5.26.1 in poerty or the associated lib.

Or using a older version as protobuf <= 5.26.0 like grpcio<=1.62.2.

With [protobuf 5.26.1](https://pypi.org/project/protobuf/#description)

[protobuf release](https://github.com/protocolbuffers/protobuf/releases/tag/v27.0-rc1)
[protobuf commit](
https://github.com/protocolbuffers/protobuf/commit/26995798757fbfef5cf6648610848e389db1fecf#diff-8de817c14d6a087981503c9aea38730b1b3e98f4e306db5ff9d525c7c304f234)

**Comment by markdoerr** [comment]
Salut @AMontagu  and @legau,

I have trouble downgrading probuf / grpcio / grpcio-tools, like @xaviave suggests.
Best would be to simply remove the deprecated line as @xaviave  suggests and as I prepared in the PR #297 .
I hope it has no cross effects (in my large application, still everything seems to work fine without the line ;) .

Is there a timeline, when you could solve this issue ? 
Merci.

**Comment by markdoerr** [comment]
> This flag has been deprecacted in the last protobuf version v27.0 and throw an exception if BaseProtoSerializer is used.
> 
> `TypeError: MessageToDict() got an unexpected keyword argument 'including_default_value_fields'`
> 
> Can be resolved with removing this line in [json_format.py:message_to_dict](https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/protobuf/json_format.py): `kwargs.setdefault("including_default_value_fields", True)` And updating protobuf >= 5.26.1 in poerty or the associated lib.
> 
> Or using a older version as protobuf <= 5.26.0 like grpcio<=1.62.2.
> 
> With [protobuf 5.26.1](https://pypi.org/project/protobuf/#description)
> 
> [protobuf release](https://github.com/protocolbuffers/protobuf/releases/tag/v27.0-rc1) [protobuf commit](https://github.com/protocolbuffers/protobuf/commit/26995798757fbfef5cf6648610848e389db1fecf#diff-8de817c14d6a087981503c9aea38730b1b3e98f4e306db5ff9d525c7c304f234)

Hi @xaviave,

I tried many different combinations of probuf / grpcio versions,
but none worked in my case, also the one you recommended (protobuf <= 5.26.0 like grpcio<=1.62.2.) other dependencies will break. Do you know the most recent version combination that one could use without showing the above error ? - protobuf changed quite a bit during time). Thanks :)
