### ISSUE TITLE
feature: documenting JSON serialisation support

### ISSUE THREAD

**Issue by markdoerr** [socotecio/django-socio-grpc#301]
Hi @AMontagu and @legau, 

I am struggeling with the serialisation of JSONFields:

Assume, I have the following model:
```
# --- model.py
class Book(models.Model):
  book_feature_json = JSONField()
```

now I would like to create a Book object:

```

from google.protobuf.struct_pb2 import Struct

book_stub.Create( book_feature_json=Struct().update( {"ISBN":"3434", "num_pages":"444}) )
```
this creation works, but the content of the book_feature_json field remains empty.

I also tried to add a JSONField serializer:

```
# serializer.py

BookProtoSerializer(proto_serializers.ModelProtoSerializer):
  book_feature_json = JSONField()
  class Meta:
        model = Book
        proto_class = ...
        proto_class_list = ...

        fields = "__all__"
```

But this also did not work - what am I missing ?

Merci :)

**Comment by AMontagu** [comment]
You have examples in tests: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/tests/test_filtering_request_struct.py#L47

Basically it's not related to DSG but to protobuf implementation in python.

The update method doesn't return anything. It update the Struct passed in parameter. So you need to do your code in 3 lines.

**Comment by markdoerr** [comment]
Merci, @AMontagu,

for the hint :) - it worked this way. I am wondering, if one could hide this extra conversion step from the user....

**Comment by AMontagu** [comment]
It would be possible to add a tooling method but IMO it will just provide more confusion from user between DSG and natif protobuf. By adding tooling we need to document it and maintain it. But if we said this is just protocol buffer people can look at protocol buffer donc that is updated when they update and using llm tool will be more coherent

**Comment by markdoerr** [comment]
This I fully understand, @AMontagu :)

If I find time, I might add one example to our DSG books example code.

Wouldn't it be useful to add a brief hint in the main DSG docs "how-to" section ("Howto send a JSON object through DSG") ? (not all people will look into the unittests (and even if they do, they might not recognise it since the example tests, you were pointing at above are more related to filtering.

Something very brief, like:
"Before sending/receiving JSON objects through gRPC, they need to be converted to and from protobuf Struct objects:

```
# sending 
from google.protobuf.struct_pb2 import Struct

data_dictionary = {"data" : "this is my data"} 
# it is important to do this in two setps, as Struct() does not return anything !!
data_as_struct = Struct()
data_as_struct.update(data_dict) 
res=  await data_stub.Create(ldata_pb2.DataRequest(data_json=data_as_struct)

# receiving
from google.protobuf.json_format import MessageToDict

res=  await data_stub.Retrieve(data_id=data_id)
data_dict = MessageToDict(res.data_json))
```

**Comment by AMontagu** [comment]
It could.
We also need to mention that this should be done only for specific use case where the data schema is not know.

**Comment by markdoerr** [comment]
That's an interesting remark, @AMontagu,
how would it look, if the (JSON) schema is known ?
