### ISSUE TITLE
Reflection APIs is not supported by the server

### ISSUE THREAD

**Issue by chapellu** [socotecio/django-socio-grpc#307]
Reflection is [a protocol](https://github.com/grpc/grpc-proto/blob/master/grpc/reflection/v1/reflection.proto) that gRPC servers can use to declare the protobuf-defined APIs they export over a standardized RPC service, including all types referenced by the request and response messages. Clients can then use this information to encode requests and decode responses in human-readable manner.

Reflection is used heavily by debugging tools such as [grpcurl](https://github.com/fullstorydev/grpcurl) and [Postman](https://learning.postman.com/docs/sending-requests/grpc/grpc-client-overview/). One coming from the REST world might compare the gRPC reflection API to serving an OpenAPI document on the HTTP server presenting the REST API being described.

https://grpc.io/docs/guides/reflection/

**Comment by AMontagu** [comment]
Sorry for the late answer.
This could be a really great feature even we didn't prioritize it. 

The main point to check is:
- Is server reflection possible to enable after the grpc server start ?

If yes we could easily find all the service used and declare them for reflection. (just adding the enable_server_reflection here: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/services/app_handler_registry.py#L137)
If no we need a way to get all the service of the server before launching the server like an extra file written by generateproto of something like that.

In both case we also need to consider that developer that use DSG may want to keep some service not reflected. This can be done with a service attribute or decorator.

**Comment by legau** [comment]
Already in #224
